const APPLICATION_ENDPOINT = `/application`;
const USER_ENDPOINT = `${APPLICATION_ENDPOINT}/user`;
const PARTY_ENDPOINT = `${APPLICATION_ENDPOINT}/party`;
const GAME_ENDPOINT = `${APPLICATION_ENDPOINT}/game`;

export default {
	USER_INFO: `${USER_ENDPOINT}/info`,
	USER_UPDATE: `${USER_ENDPOINT}/update`,
	PARTY_LIST: `${PARTY_ENDPOINT}/list`,
	PARTY_INFO: `${PARTY_ENDPOINT}/info`,
	PARTY_CREATE: `${PARTY_ENDPOINT}/create`,
	PARTY_JOIN: `${PARTY_ENDPOINT}/join`,
	PARTY_LEAVE: `${PARTY_ENDPOINT}/leave`,
	GAME_CREATE: `${GAME_ENDPOINT}/create`,
	GAME_READY: `${GAME_ENDPOINT}/ready`,
}