package com.dainws.games.cbg.domain.communication;

public enum EventCode {
	GAME_CREATED,
	GAME_START, GAME_END,
	PLAYER_WIN, PLAYER_LOSE, PLAYER_SURRENDER,
	PLAYER_GET_TURN, PLAYER_GET_CARD,
	PLAYER_PUT_CARD, PLAYER_MOVE_CARD,
	PLAYER_ATTACK_CARD, PLAYER_EQUIP_CARD,
	PLAYER_USE_SPELL, PLAYER_PASS_TURN;
	
	
}
