export default {
    GAME_CREATED: 'GAME_CREATED',
    GAME_START: 'GAME_START',
    GAME_END: 'GAME_END',
    PLAYER_WIN: 'PLAYER_WIN', 
    PLAYER_LOSE: 'PLAYER_LOSE', 
    PLAYER_SURRENDER: 'PLAYER_SURRENDER',
    PLAYER_GET_TURN: 'PLAYER_GET_TURN', 
    PLAYER_GET_CARD: 'PLAYER_GET_CARD',
    PLAYER_PUT_CARD: 'PLAYER_PUT_CARD', 
    PLAYER_MOVE_CARD: 'PLAYER_MOVE_CARD',
    PLAYER_ATTACK_CARD: 'PLAYER_ATTACK_CARD', 
    PLAYER_EQUIP_CARD: 'PLAYER_EQUIP_CARD',
    PLAYER_USE_SPELL: 'PLAYER_USE_SPELL', 
    PLAYER_PASS_TURN: 'PLAYER_PASS_TURN'
}