import EventCodes from "./EventCodes";

const EventProcessors = new Map()
EventProcessors.set(EventCodes.GAME_CREATED, )
EventProcessors.set(EventCodes.GAME_START, )
EventProcessors.set(EventCodes.GAME_END, )
EventProcessors.set(EventCodes.PLAYER_WIN, )
EventProcessors.set(EventCodes.PLAYER_LOSE, )
EventProcessors.set(EventCodes.PLAYER_SURRENDER, )
EventProcessors.set(EventCodes.PLAYER_GET_TURN, )
EventProcessors.set(EventCodes.PLAYER_GET_CARD, )
EventProcessors.set(EventCodes.PLAYER_PUT_CARD, )
EventProcessors.set(EventCodes.PLAYER_MOVE_CARD, )
EventProcessors.set(EventCodes.PLAYER_ATTACK_CARD, )
EventProcessors.set(EventCodes.PLAYER_EQUIP_CARD, )
EventProcessors.set(EventCodes.PLAYER_USE_SPELL, )
EventProcessors.set(EventCodes.PLAYER_PASS_TURN, )