@startuml
title "Domain Model - Statistics"

rectangle Statistic

rectangle Damage
rectangle TrueDamage
rectangle PhysicalDamage
rectangle MagicalDamage
rectangle InfiniteDamage

rectangle Health
rectangle InfiniteHealth
rectangle MaxValue

rectangle Armor
rectangle PhysicalArmor
rectangle MagicalArmor

rectangle Value

Statistic *--> Value
Statistic <|-- Damage
Statistic <|-- Health
Statistic <|-- Armor

Damage <|-- TrueDamage
Damage <|-- PhysicalDamage
Damage <|-- MagicalDamage

TrueDamage o--> "0..1" InfiniteDamage

Health *--> MaxValue
Health o--> "0..1" InfiniteHealth

Armor <|-- PhysicalArmor
Armor <|-- MagicalArmor

note as DamageNote
 Damage cant be negative
 
 - **PhysicalDamage** ignores Magical armor.
	- **MagicalDamage** ignores Physical armor.
	- **TrueDamage** ignores Physical and Magical armor.
	- **InfiniteDamage** ignores all type of armor and Infinite health.
end note
Damage ... DamageNote

note as ArmorNote 
	It will defend against an **attack** 
	**of the same type**, but its value 
	will be **permanently reduced** by 
	the value of the **defended attack**
end note
Armor ... ArmorNote

note as HealthNote
	When Health reaches 0 or less, 
	then combatant die

	It can only be reduced 
	by damage when **armor**
	**reaches a value of 0**,
	or with **True damage** 
end note
Health ... HealthNote

@enduml