@startuml
title "Domain Model - Game"

rectangle Game
rectangle Player
rectangle Action
rectangle Dealer
rectangle Board
rectangle Card

rectangle Round
rectangle Turn

Game *--> Turn
Game *--> Round
Game *--> Dealer
Game *--> Board
Game *--> "2..N" Player

Round --> Turn

Turn --> Player

Dealer --> Round
Dealer --> Card : Dealt

Board o--> Card
Card ..> Player : Deal to

Player --> Action
@enduml