@startuml
title "Domain Model - Game"

class Game {}
class Player {}
class Action {}
class Dealer {}
class Board {}
class Card {}

Game *--> Turn
Game *--> Round
Game *--> Dealer
Game *--> Board
Game *--> "2..N" Player

Round --> Turn

Turn --> Player

Dealer --> Round
Dealer --> Card : Dealt

Board o--> Card
Card ..> Player : Deal to

Player --> Action
@enduml