@startuml 
title Usecases - Acciones del usuario
left to right direction

:Player: --> (Poner carta)
:Player: --> (Mover carta)
:Player: --> (Usar carta)
:Player: --> (Equipar carta)
:Player: --> (Atacar carta)
:Player: --> (Pasar turno)
:Player: --> (Rendirse)

:Party Owner: --> (Start party game)
:User: --> (Create party)
:User: --> (Join party)
:User: --> (Leave party)
:Anonymous: --> (Create session)
@enduml