@startuml
title "Domain model"
!theme plain

CardBattleGame *--> Turn
CardBattleGame *--> Round
CardBattleGame *--> "2..N" Player
CardBattleGame *--> Dealer

Turn --> Player : Over

Round --> DealStrategy : Define
Dealer ..> DealStrategy
Dealer *--> Deck
DealStrategy ..> Card : Deal
Deck *--> " 1..N" Card

Player *--> Leader
Player *--> Zone
Player *--> Hand

Zone *---> "2" Row
Row *--> "3" Square
Square o--> "0..1" Warrior
Hand o---> "0..N  " Card

Card <|-- Spell
Card <|-- Warrior
Card <|-- Equipment

Warrior *--> WarriorType
WarriorType <|--- Common
WarriorType <|--- Uncommon
WarriorType <|--- Rare
WarriorType <|--- Epic
WarriorType <|--- Legendary
WarriorType <|--- Mithic

Spell --> Effect : Causes
Spell *--> TriggerCondition
TriggerCondition <|-- RoundCondition
TriggerCondition <|-- UseSpellCondition
TriggerCondition <|-- AdquireCardCondition

Warrior o--> "0..1" Equipment

Player o--> "0..N" Action
Action <|-- CardAction
Action <|-- Surrender
CardAction ..> Card : Selected
CardAction <|-- UseSpell
CardAction <|-- UseEquipment
CardAction <|-- WarriorAction

UseEquipment .-.> Square : Target
WarriorAction .-.> Square : Target
WarriorAction <|-- Put
WarriorAction <|-- Move
WarriorAction <|-- Attack

Move ..> Square : From

Class UseSpell {
 Must have a 
 Spell card type
}
@enduml