@startuml
Title domain analysis

Class Game {}

Class RoundZero {
 1 Leader
}

Class RoundOne {
 2 Warrior Pop
}

Class RoundTwo {
 1 Warrior Pop
 1 Warrior Common
}

Class RoundThree {
 1 Spell
}

Class RoundFour {
 1 Warrior Rare
}

Class RoundFive {
 1 Spell
 1 Warrior Rare
}

Class RoundSix {
 1 Warrior Epic
}

Class RoundUnknown {
 1 Spell
}

Game -- "2..N" Player
Game --> Deck
Game --> Round
Round <|-- RoundZero
Round <|-- RoundOne
Round <|-- RoundTwo
Round <|-- RoundThree
Round <|-- RoundFour
Round <|-- RoundFive
Round <|-- RoundSix
Round <|-- RoundUnknown

'====================================== Players

Class Player {
 Name "Mandatory"
 BirthDate "Mandatory"
}

'====================================== Decks

Class Deck {}

Deck -L- "1..N" Card

'====================================== Cards

Class Card {
 Name "Mandatory"
 Description "Mandatory"
}

Class LeaderCard {
 Health "Mandatory"
}

Class SpellCard {
 Special ability "Mandatory"
}

Class EquipmentCard {
 Special ability "Optional"
 Health "Mandatory"
 HealthPerTurn "Optional"
}

Class WarriorCard {
 Special ability "Optional"
 Health "Mandatory"
 HealthPerTurn "Optional"
}

Card <|-- LeaderCard
Card <|-- EquipmentCard
Card <|-- SpellCard
Card <|-- WarriorCard

LeaderCard ---> Damage
EquipmentCard --- "0..2" Damage
EquipmentCard --- "0..2" Armor
WarriorCard --- "0..2" Damage
WarriorCard --- "0..2" Armor

Damage <|-- "0..1" PhysicalDamage
Damage <|-- "0..1" MagicDamage

Armor <|-- "0..1" PhysicalArmor
Armor <|-- "0..1" MagicArmor

WarriorCard ----> WarriorType
WarriorType <|-- Pop
WarriorType <|-- Common
WarriorType <|-- Rare
WarriorType <|-- Epic
WarriorType <|-- Legendary
@enduml