@startuml
title "Analysis - Battle card game"
!theme plain

CardBattleGame *--> Turn
CardBattleGame *--> Round
CardBattleGame *--> "2..N" Player
CardBattleGame *--> Dealer

Turn --> Player
DealStrategy --> Deck

Player *--> Leader
Player *--> Zone
Zone *---> "2" Row
Row *--> "3" Square
Square o--> "0..1" Warrior

Player *--> Hand
Hand o--> "0..N" Card

Dealer o--> DealStrategy
Dealer *--> Deck
DealStrategy --> Round
Deck *--> "1..N" Card

Card <|-- Spell
Card <|-- Warrior
Card <|-- Equipment

Warrior *--> WarriorType
WarriorType <|--- Common
WarriorType <|--- Uncommon
WarriorType <|--- Rare
WarriorType <|--- Epic
WarriorType <|--- Legendary
WarriorType <|--- Mithic

Spell --> Effect : Causes
Effect .u.> CardBattleGame : Affect

Warrior o--> "0..1" Equipment

Player o--> "0..N" Action
Action <|-- Surrender
Action <|-- CardAction
CardAction ..> Card : Selected
CardAction <|-- UseSpell
CardAction <|-- UseEquipment
CardAction <|-- WarriorAction

UseEquipment .-.> Square : Target
WarriorAction .-.> Square : Target
WarriorAction <|-- Put
WarriorAction <|-- Move
WarriorAction <|-- Attack

Move ..> Square : From
@enduml